# Generated by Django 3.2.6 on 2021-08-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
